# -*- coding: utf-8 -*-
"""Untitled9.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1r0_OSezMGRsGtHnnvc55HyBhk5HSoS0w
"""

import pandas as pd
from datetime import date
import json

# ===============================
# Unified Keyword Dictionary
# ===============================
CATEGORY_KEYWORDS = {
    "donation": {
        "en": ["blood donation", "blood donor", "blood bank", "blood donor recruitment programme", "national blood programme"],
        "zh": ["捐血", "献血", "血库"],
        "ms": ["derma darah", "bank darah", "penderma darah"],
        "ta": ["இரத்த தானம்", "இரத்த வங்கி", "இரத்தக் கொடையாளர்",
               "இரத்தக் கொடையாளர் சேர்த்தல் திட்டம்", "தேசிய இரத்தத் திட்டம்",
               "இரத்த தான முகாம்", "நடமாடும் இரத்த தான ஊர்தி",
               "இரத்த தானத் தோழன்", "இரத்த தானத் தோழி"]
    },
    "health": {
        "en": ["first aid", "cpr", "aed", "ambulance service", "medical chaperone", "transportaid"],
        "zh": ["急救", "心肺复苏", "救护车", "医疗陪同"],
        "ms": ["pertolongan cemas", "ambulans", "pengiring perubatan"],
        "ta": ["முதலுதவி", "முதலுதவி சிகிச்சை", "சிபிஆர்", "ஆம்புலன்ஸ்",
               "சைக்கிள் முதலுதவி சேவை", "போக்குவரத்து உதவி",
               "மருத்துவத் துணை மற்றும் போக்குவரத்து சேவை",
               "இதய நுரையீரல் புத்துயிர்ப்பு", "உளவியல் முதலுதவி"]
    },
    "community": {
        "en": ["elder aid", "food aid", "transport aid", "disabled", "home monitoring and eldercare"],
        "zh": ["老年人", "食物援助", "交通援助", "残疾人"],
        "ms": ["warga emas", "makanan bantuan", "pengangkutan bantuan", "orang kurang upaya"],
        "ta": ["மூத்தவர்", "முதியோர் உதவி", "உணவு உதவி", "போக்குவரத்து உதவி",
               "ஊனமுற்றவர்", "வீட்டு கண்காணிப்பு மற்றும் முதியோர் பராமரிப்பு",
               "நடமாடும் மருத்துவமனை",
               "செஞ்சிலுவைச் சங்கம் | அமைப்பு", "நிறுவனம்", "தன்னார்வத் தொண்டு நிறுவனம்"]
    },
    "event": {
        "en": ["red cross youth", "red cross junior", "volunteer", "cca", "international bazaar"],
        "zh": ["红十字青年", "红十字少年", "义工", "课外活动"],
        "ms": ["belia palang merah", "pelajar junior palang merah", "sukarelawan", "aktiviti kokurikulum"],
        "ta": ["ரெட் கிராஸ் இளைஞர்கள்", "ரெட் கிராஸ் ஜூனியர்", "தன்னார்வலர்", "சிசிஏ",
               "செஞ்சிலுவை இளையர் பிரிவு", "சமூகச் செஞ்சிலுவை இளையர்",
               "சிங்கப்பூர் செஞ்சிலுவை இளையர் பிரிவு"]
    },
    "other": {
        "en": ["organ transplant", "blood transfusion", "philanthropy", "habitat for humanity", "mercy relief",
               "Care & Share", "ComCare", "SG Enable"],
        "zh": ["器官移植", "输血", "慈善", "仁爱之家"],
        "ms": ["pemindahan organ", "derma organ", "filantropi"],
        "ta": ["உறுப்பு மாற்று அறுவை சிகிச்சை", "உறுப்பு தானம்", "உறுப்பு மாற்று நிராகரிப்பு",
               "உறுப்பு மாற்றில் புதிய முன்னேற்றங்கள்", "உறுப்பு மாற்றுச் சிக்கல்கள்",
               "உறுப்பு மாற்று மருத்துவமனைகள்", "அவசர உறுப்பு மாற்று",
               "இரத்தமேற்றுதல்", "முதியோர் பராமரிப்பு", "முதியோர் மக்கள் தொகை",
               "பகிர்ந்து கொள்வோம் மற்றும் பராமரிப்போம்", "காம்கேர்",
               "ஹபிடாட் ஃபார் ஹியூமானிட்டி", "மனிதநேயத்திற்கான வாழ்விடம்",
               "சர்வதேச செஞ்சிலுவைச் சங்கக் குழு", "ஐசிஆர்சி",
               "சர்வதேச செஞ்சிலுவை மற்றும் செம்பிறை சங்கங்களின் கூட்டமைப்பு",
               "மெர்சி ரிலீஃப்", "கருணை நிவாரணம்",
               "சிங்கப்பூர் சர்வதேச அறக்கட்டளை", "எமது சிறந்த உலகம்", "எஸ்ஐஎஃப் கனெக்ட்",
               "தி ரெட் பென்சில் சிங்கப்பூர்"]
    }
}

# ===============================
# Classification Function
# ===============================
def classify_article(text: str) -> dict:
    text = text.lower()
    for category, langs in CATEGORY_KEYWORDS.items():
        for lang, keywords in langs.items():
            if any(kw.lower() in text for kw in keywords):
                return {
                    "keyword_category": category,
                    "language": lang
                }
    return {
        "keyword_category": "other",
        "language": "en"  # default fallback
    }

# ===============================
# Metadata Schema
# ===============================
METADATA_SCHEMA = {
    "title": {"type": str, "required": True},
    "date_published": {"type": date, "required": True},
    "author": {"type": str, "required": False},
    "source": {"type": str, "required": True},
    "keyword_category": {"type": str, "required": True, "allowed": ["donation", "health", "community", "event", "other"]},
    "language": {"type": str, "required": True, "allowed": ["en", "zh", "ms", "ta"]}
}

# ===============================
# Data Cleaning + Classification Pipeline
# ===============================
#Load JSON file
with open("media_documents.json", "r", encoding="utf-8") as f:
    data = json.load(f)

df = pd.DataFrame(data)

# Auto-classify each article text
df[["keyword_category", "language"]] = df["title"].apply(lambda t: pd.Series(classify_article(t)))

#Check required columns (warn and continue)
required_fields = [field for field, rules in METADATA_SCHEMA.items() if rules.get("required")]
missing_cols = set(required_fields) - set(df.columns)

if missing_cols:
    print(f"Warning: Missing required columns: {missing_cols}")
    with open("missing_fields_log.json", "w", encoding="utf-8") as f:
        json.dump({"missing_columns": list(missing_cols)}, f, ensure_ascii=False, indent=2)

# Enforce allowed values
for field, rules in METADATA_SCHEMA.items():
    if "allowed" in rules and field in df.columns:
        df = df[df[field].isin(rules["allowed"]) | df[field].isna()]

# Enforce data types
for field, rules in METADATA_SCHEMA.items():
    if field not in df.columns:
        continue
    expected_type = rules["type"]
    if expected_type == str:
        df[field] = df[field].astype(str)
    elif expected_type == date:
        df[field] = pd.to_datetime(df[field], errors="coerce").dt.date

# Drop rows missing required values (with logging)
before_drop = len(df)
dropped_rows = df[df[required_fields].isna().any(axis=1)]
if not dropped_rows.empty:
    dropped_rows.to_json("dropped_records.json", orient="records", force_ascii=False, indent=2)
    print(f" Dropped {len(dropped_rows)} rows due to missing required values. Logged to dropped_records.json")

df = df.dropna(subset=required_fields)
after_drop = len(df)

# Save cleaned + classified JSON
df.to_json("media_documents_clean.json", orient="records", force_ascii=False, indent=2)

print(f"Schema-compliant JSON saved: {len(df)} records (started with {before_drop}, dropped {before_drop - after_drop})")